In [22]:
import numpy as np
import pandas as pd


# create some data with null value ( f1, f2, status)
data = {
    'f1': [1, np.nan, 3, 4, 5, 6, 7, 8, 9, 10],
    'f2': [1, 2, 3, 4, np.nan, 6, 7, 8, 9, 10],
    'f3': ['A','A','B','A','B','A','B','A','B','A'],
    'status': ['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)
df

     f1    f2 f3 status
0   1.0   1.0  A    Yes
1   NaN   2.0  A     No
2   3.0   3.0  B    Yes
3   4.0   4.0  A     No
4   5.0   NaN  B    Yes
5   6.0   6.0  A     No
6   7.0   7.0  B    Yes
7   8.0   8.0  A     No
8   9.0   9.0  B    Yes
9  10.0  10.0  A     No

In [23]:
# mean imputations
df['f1'] = df['f1'].fillna(df['f1'].mean())
df['f2'] = df['f2'].fillna(df['f2'].mean())
df

          f1         f2 f3 status
0   1.000000   1.000000  A    Yes
1   5.888889   2.000000  A     No
2   3.000000   3.000000  B    Yes
3   4.000000   4.000000  A     No
4   5.000000   5.555556  B    Yes
5   6.000000   6.000000  A     No
6   7.000000   7.000000  B    Yes
7   8.000000   8.000000  A     No
8   9.000000   9.000000  B    Yes
9  10.000000  10.000000  A     No

In [30]:
pd.get_dummies(df['f3'])

       A      B
0   True  False
1   True  False
2  False   True
3   True  False
4  False   True
5   True  False
6  False   True
7   True  False
8  False   True
9   True  False

In [ ]:
# you need to apply OHE for categorical data
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
test = ohe.fit_transform(df[['f3']])

df = pd.concat([df, pd.DataFrame(test.toarray())], axis=1)

ValueError: Length mismatch: Expected axis has 6 elements, new values have 5 elements

In [25]:
df.columns = ['f1', 'f2', 'f3','status', 'A', 'B']

In [28]:
X =df[['f1', 'f2', 'A', 'B']]
Y= df['status']

In [29]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, Y)

KNeighborsClassifier(n_neighbors=3)